cursovafront/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls') ),
]

homepage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import OrderList, OrderDetail, CreateOrder, DeleteOrder, CustomLoginView, СatalogueView, AdminPage
from django.contrib.auth.views import LogoutView
from django.urls import include
from django.contrib import admin


# urlpatterns = [
#     path('', views.homepage, name='homepage'),
# ]

urlpatterns = [
    path('order-create/', CreateOrder.as_view(), name='order-create'),
    path('order/', OrderList.as_view(), name='order'),
    path('', views.homepage, name='homepage'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('order/<int:pk>/', OrderDetail.as_view(), name='order-detail'),
    path('order-delete/<int:pk>/', DeleteOrder.as_view(), name='order-delete'),
    path('catalogue/', СatalogueView.as_view(), name='catalogue'),

    path('admin-page/', AdminPage.as_view(), name='admin-page'),
]

homepage/models.py
# Create your models here.
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    """Продукт"""

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукти"

    product_name = models.TextField(verbose_name="Назва продукту")
    wine_type = models.TextField(verbose_name="Тип")
    quantity_on_plant = models.IntegerField(verbose_name="Кількість на заводі")
    created_at = models.DateTimeField(verbose_name="Дата виготовлення", auto_now_add=True)
    price = models.IntegerField(verbose_name="Ціна (грн)")
    price_for_all = models.IntegerField(verbose_name="Ціна за всі одиниці продукту (грн)")
    surovuna_id = models.ForeignKey("Surovuna", on_delete=models.CASCADE, verbose_name="Ідентифікатор сировини")

    def __str__(self):
        return f"{self.product_name}"


# class Customer(models.Model):
#     """Покупець (власник винного магазину)"""

#     class Meta:
#         db_table = "customer"
#         verbose_name = "Дані про замовника"
#         verbose_name_plural = "Дані про замовників"

#     customer_name = models.TextField(verbose_name="Ім'я замовника")
#     phone = models.TextField(verbose_name="Номер телефону")
#     email = models.TextField(verbose_name="Електронна пошта")
#     # password = models.TextField(verbose_name="Пароль")
#     city = models.TextField(verbose_name="Місто замовника")
#     new_post_number = models.TextField(verbose_name="Номер відділення нової пошти")

#     def __str__(self):
#         return self.customer_name



class Surovuna(models.Model):
    """Сировина"""

    class Meta:
        db_table = "surovuna"
        verbose_name = "Сировина"
        verbose_name_plural = "Сировина"


    surovuna_name = models.TextField(verbose_name="Назва сировини")
    quantity_on_plant = models.IntegerField(verbose_name="Кількість сировини на заводі (тонн)")
    vurobnucha_price_kg = models.IntegerField(verbose_name="Ціна за кілограм сировини (грн)")
    vurobnucha_price_general_kg = models.IntegerField(verbose_name="Загальна ціна за сировину (грн)")
    delivery_price = models.IntegerField(verbose_name="Ціна доставки (грн)")
    delivery_name = models.TextField(verbose_name="Постачальник")


    def __str__(self):
        return f"{self.surovuna_name}"


STATUS_CHOICES = [
        ("Відкрито", "Відкрито"),
        ("Закрито", "Закрито"),
        ("В роботі", "В роботі"),
        ("Потребує уточнення", "Потребує уточнення"),
    ]

class Order(models.Model):
    """Замовлення"""

    class Meta:
        db_table = "order"
        verbose_name = "Замовлення"
        verbose_name_plural = "Замовлення"

    user_id = models.ForeignKey(User, verbose_name="Замовник", on_delete=models.CASCADE, default=1)
    product_id = models.ForeignKey(Product, verbose_name="Продукт", on_delete=models.CASCADE)
    quantity_of_product = models.IntegerField(verbose_name="Кількість продукту")
    created_at = models.DateTimeField(verbose_name="Дата замовлення", auto_now_add=True)
    last_updated_at = models.DateTimeField(verbose_name="Востаннє змінено", blank=True, null=True)
    order_status = models.CharField(max_length=20, verbose_name="Статус замовлення", choices=STATUS_CHOICES, default="open")


    def save(self, *args, **kwargs):
        self.last_updated_at = datetime.now()
        super().save(*args, **kwargs)

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import Order, Product, Surovuna
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy


def homepage(request):
    return render(request, 'homePage.html')


class OrderList(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'userPage.html'
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = context['order'].filter(user_id=self.request.user)
        context['count'] = context['order'].exclude(order_status="Закрито").count()    # кількість замовлень з не закритим статусом
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['order'] = context['order'].filter(product_id__product_name__icontains=search_input)
            context['search_input'] = search_input
        return context



class OrderDetail(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'order_detail.html'
    context_object_name = 'order'

    def get_object(self, queryset=None):
        queryset = super().get_queryset().select_related('product_id')
        return get_object_or_404(queryset, id=self.kwargs['pk'])



class CreateOrder(LoginRequiredMixin, CreateView):
    model = Order
    template_name = 'order_form.html'
    fields = ['product_id', 'quantity_of_product']
    # fields = "__all__"
    success_url = reverse_lazy('order')

    def form_valid(self, form):
        form.instance.user_id = self.request.user
        return super(CreateOrder, self).form_valid(form)



class DeleteOrder(LoginRequiredMixin, DeleteView):
    model = Order
    context_object_name = 'order'
    template_name = 'order_delete.html'
    success_url = reverse_lazy('order')



# class CustomLoginView(LoginView):
#     template_name = 'login.html'
#     fields = "__all__"
#     redirect_authenticated_user = False

#     def get_success_url(self):
#         return reverse_lazy('order')


class CustomLoginView(LoginView):
    template_name = 'login.html'
    fields = "__all__"
    redirect_authenticated_user = False

    def get_success_url(self):
        if self.request.user.is_superuser:  # перевіряємо, чи користувач має права адміністратора
            return reverse_lazy('admin-page')  # якщо має, то перенаправляємо на сторінку адміністратора
        else:
            return reverse_lazy('order')  # якщо ні, то перенаправляємо на сторінку зі списком замовлень



class СatalogueView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalogue.html'
    context_object_name = 'product'



class AdminPage(LoginRequiredMixin, ListView):
    template_name = 'admin_page.html'
    context_object_name = 'orders'

    def get_queryset(self):
        orders = Order.objects.all()
        products = Product.objects.all()
        surovunas = Surovuna.objects.all()
        return {'orders': orders, 'products': products, 'surovunas': surovunas}

homepage/templates/admin_page.html
{% extends 'main.html' %}

{% block content %}
    <h1>Замовлення:</h1>
    <ul>
        {% for order in orders %}
            <li>{{ order }}</li>
        {% endfor %}
    </ul>

    <h1>Товари:</h1>
    <ul>
        {% for product in products %}
            <li>{{ product }}</li>
        {% endfor %}
    </ul>

    <h1>Сировина:</h1>
    <ul>
        {% for surovuna in surovunas %}
            <li>{{ surovuna }}</li>
        {% endfor %}
    </ul>
{% endblock %}

homepage/templates/catalogue.html
{% extends 'main.html' %}

{% block content %}
<div class="header-bar">
    <h1>Каталог продуктів</h1>
    <a href="{% url 'order' %}">&#215;</a>
</div>

{% if product %}
<div class="table">
    <ul>
        {% for prod in product %}
        <li>
            <h3>{{ prod.product_name }}</h3>
            <p>Тип: {{ prod.wine_type }}</p>
            <p>Додано на сайт: {{ prod.created_at }}</p>
            <p>Сировина: {{ prod.surovuna_id }}</p>
            <p>Ціна: {{ prod.price }} грн.</p>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Продукти не знайдені.</p>
    {% endif %}
</div>

<style>
    ul {
        list-style-type: none;
        margin-right: 40px;
    }

    li {
        border: 1px solid black;
        padding: 20px 220px 20px 20px;
        margin-bottom: 10px;
        margin: 20px;
    }

    h3 {
        margin-bottom: 10px;
        color: #9c1200;
    }
    
    .table {
        display: flex;
        margin-bottom: 100px;
    }
</style>
{% endblock %}

homepage/templates/homePage.html
<!DOCTYPE html>
<html>

<head>
    <title>Виноградний рай</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />

</head>

<body>
    {% block content %}

    <div id="first-list">
        <nav>
            <ul>
                <li><a href="#first-list">ГОЛОВНА</a></li>
                <li><a href="#second-list">ПРО НАС</a></li>
                <li><a href="#third-list">НОВИНКИ</a></li>
                <li><a href="#BlockInfo">КОНТАКТИ</a></li>
            </ul>
            <a id="intrance" href="{% url 'login' %}">УВІЙТИ</a>
           
        </nav>

        <div class="container">
            <div class="elem">
                <h1>ВИНО ДЛЯ НАСОЛОДИ ДУШІ ТА ТІЛА</h1>
                <p>Віднайди свій смак</p>
                <button class="butnWatch" style="margin-top: 50px;"><a href="#third-list">ПЕРЕГЛЯНУТИ</a></button>
            </div>
        </div>

        <!-- <section class="home" id="#content">
            <div class="form_container">
                <i class="uil uil-times form_close"></i>
                <div class="form login_form">
                    <form action="#">
                        <h2>Вхід</h2>
                        <div class="input_box">
                            <input type="email" placeholder="Електронна пошта" required />
                        </div>
                        <div class="input_box">
                            <input type="password" placeholder="Пароль" required />
                            <i class="uil uil-eye-slash pw_hide"></i>
                        </div>
                        <div class="option_field">
                            <a href="#" class="forgot_pw">Забули пароль?</a>
                        </div>
                        <button class="button">Увійти</button>
                    </form>
                </div>
            </div>
        </section> -->
    </div>

    <div id="second-list">
        <div class="side second-list-left">
            <div id="main-box">
                <div class="box card-box">
                    <div class="box front-box"></div>
                    <div class="box back-box"></div>
                </div>
            </div>
        </div>

        <div class="side second-list-right">
            <h6>ПРО НАС</h6>
            <p>Винний завод "Виноградний рай" почав свою історію далеко в 1975 році,
                коли група друзів з міста Києва вирішила взятися за виробництво
                вина на власному подвір'ї. Початкові експерименти були не дуже
                успішними, але натхненість і наполегливість підштовхнули їх
                до подальшого розвитку проекту.</p>
            <p>У 1980-х роках компанія зробила величезний крок вперед, коли вони зуміли
                здобути додатковий капітал та купити ділянку з виноградниками в Херсонській
                області. З того часу компанія почала активно розвиватися та створювати
                вина високої якості з регіону.</p>
            <p>Сьогодні "Виноградний рай" є одним з провідних виробників вина в
                Україні та експортує свої продукти до країн Європи, Азії та Північної
                Америки. Місія компанії полягає у виробництві якісних вин та збереженні
                національних традицій виноробства. У своїй діяльності компанія
                дотримується цінностей, таких як екологічна чистота, відповідальність
                перед споживачами та партнерами, добросовісність та прозорість.</p>
            <button class="btnNovunku" style="margin-top: 40px; margin-left: 50px;"><a href="#third-list">НОВИНКИ</a></button>
        </div>
    </div>

    <div id="third-list">
        <div class="side third-list-left">
            <h1>НОВИНКИ</h1>
            <div class="table-third-list-on-black">
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th>Вино</th>
                            <th>Алкоголю</th>
                            <th>Цукру</th>
                            <th>Ємність</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><img src="../static/img/1.webp" alt="Вино"></td>
                            <td>Стефанія</td>
                            <td>12%</td>
                            <td>7%</td>
                            <td>1.5</td>
                        </tr>
                        <tr>
                            <td><img src="../static/img/2.jpg" alt="Вино"></td>
                            <td>Мускат</td>
                            <td>11%</td>
                            <td>3%</td>
                            <td>0.75</td>
                        </tr>
                        <tr>
                            <td><img src="../static/img/3.jpg" alt="Вино"></td>
                            <td>Брют</td>
                            <td>12.5%</td>
                            <td> - </td>
                            <td>0.75</td>
                        </tr>
                        <tr>
                            <td><img src="../static/img/4.jpg" alt="Вино"></td>
                            <td>Бренді</td>
                            <td>40%</td>
                            <td> - </td>
                            <td>0.5</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="side third-list-right">
            <div class="table-third-list-on-img">
                <table>
                    <thead>
                        <tr>
                            <th>Опис</th>
                            <th>Ціна</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Червоне напівсолодке. Серія: Бордо</td>
                            <td><b>113грн</b></td>
                        </tr>
                        <tr>
                            <td>Мікс білих та червоних вин. Серія: Select</td>
                            <td><b>124грн</b></td>
                        </tr>
                        <tr>
                            <td>Шампанське. Колір: Біле</td>
                            <td><b>159грн</b></td>
                        </tr>
                        <tr>
                            <td>Серія: Бренді</td>
                            <td><b>175грн</b></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="fourth-list">
        <div id="BlockInfo">
            <p>
                Контакти <br /><br />
                +38 (032) 235-55-83 (адміністрація)<br />
                +38 (096) 689-79-81 (адміністрація)<br />
                +38 (032) 235-67-62 (адміністрація)
            </p>
            <ul class="social-media">
                <li><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                <li><a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a></li>
                <li><a href="https://telegram.org/"><i class="fa fa-telegram"></i></a></li>
              </ul>
            <p>
                Адреса<br /><br />
                вулиця Виноградна, 1<br />
                вулиця Бочкова, 12<br />
                Херсонська область
            </p>
        </div>
    </div>
    <!-- <script src="{% static 'js/script.js' %}"></script> -->
    <!-- <script src="../static/js/script.js"></script> -->
</body>
</html>
{% endblock content %}

homepage/templates/login.html
{% extends 'main.html' %}

{% block content %}

<div class="header-bar">
    <h1>Вхід</h1>
    <a href="{% url 'homepage' %}">&#215;</a>
</div>

<div class="card-body">
    <form method="post">
        {% csrf_token %}
        <div>
            <input type="text" name="{{ form.username.name }}" id="{{ form.username.id_for_label }}"
                placeholder="Ім'я користувача" required>
        </div>
        <div>
            <input type="password" name="{{ form.password.name }}" id="{{ form.password.id_for_label }}"
                placeholder="Пароль" required>
            <i class="fa fa-eye-slash pw_hide"></i>
        </div>
        <input class="button" type="submit" value="Увійти">
    </form>
</div>

<style>
    i {
        position: absolute;
        top: 50.4%;
        right: 39.5%;
        transform: translateY(-50%);
        font-size: 20px;
        color: #707070;
    }

    .pw_hide {
        font-size: 15px;
    }

    label {
        display: none;
    }

    .header-bar {
        background: white;
        height: 20px;
        margin-bottom: 50px;
    }

    .header-bar h1 {
        margin-left: 245px;
        color: black;
        font-style: normal;
        text-shadow: none;
        font-weight: 1000;
        font-size: 40px;
    }

    .header-bar a {
        color: black;
    }

    .button {
        margin-top: 80px;
        width: 20%;
    }
</style>

<script>
    const pwShowHide = document.querySelectorAll(".pw_hide");

    pwShowHide.forEach((icon) => {
        icon.addEventListener("click", () => {
            let getPwInput = icon.parentElement.querySelector("input");
            if (getPwInput.type === "password") {
                getPwInput.type = "text";
                icon.classList.replace("uil-eye-slash", "uil-eye");
            } else {
                getPwInput.type = "password";
                icon.classList.replace("uil-eye", "uil-eye-slash");
            }
        });
    });
</script>

{% endblock content %}

homepage/templates/main.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Виноградний рай</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <!-- шрифти -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <!-- іконки -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
</head>

<style>
    body {
        /* background: linear-gradient(90deg, #ff00bf9b 0%, #c6ff6932 43%, #0099ff9d 100%); */
        font-family: 'Nunito', sans-serif;
        padding-top: 110px;

        background-image: url("/static/img/RedWineHeader.png");
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }

    .container {
        max-width: 650px;
        margin: auto;
        background-color: #fff;
        -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        border-radius: 20px;
        opacity: 0.9;
    }

    .header-bar {
        display: flex;
        justify-content: space-between;
        color: #fff;
        padding: 30px;
        border-radius: 20px 20px 0 0;
        /* background: linear-gradient(90deg, #008cff 0%, #d469ff 43%, #ff00bf 100%); */
        background-image: url("/static/img/texture.jpg");
        background-size: cover;
    }

    .header-bar h3 {
        font-size: 18px;
        font-style: italic;
        text-shadow: 2px 2px 3px #000000;
        padding-left: 10px;
    }

    .header-bar a {
        color: rgb(247, 247, 247);
        text-decoration: none;
        font-size: 22px;
        margin-top: 27px;
    }

    #user_icon:hover {
        text-decoration: underline;
    }

    .header-bar p {
        font-size: 18px;
        font-style: italic;
        text-shadow: 2px 2px 3px #000000;
    }

    .fa-sign-out-alt,
    .catalog-icon {
        color: white;
        font-size: 20px;
        margin-left: 18px;
        margin-right: 30px;
        margin-bottom: 10px;
    }

    .fa-search {
        color: white;
        font-size: 12px;
    }

    .fa-trash {
        color: #9c1200;
        font-size: 20px;
    }

    h1 {
        font-size: 30px;
        font-style: italic;
        text-shadow: 2px 2px 3px #000000;
        color: #fff;
        padding-left: 10px;
    }

    .task-wrapper {
        display: flex;
        align-items: center;
        justify-content: space-between;
        background-color: #fff;
        border-top: 1px solid #dfe4ea;
        overflow: hidden;
        padding-left: 10px;
        padding-right: 10px;
        border-radius: 0 0 20px 20px;
    }

    .task-wrapper h3 {
        margin-left: 20px;
    }

    .task-title {
        display: flex;
        padding: 20px;
    }

    .task-title a {
        text-decoration: none;
        color: #4b5156;
        margin-left: 10px;
    }

    .task-complete-icon {
        height: 20px;
        width: 20px;
        background-color: rgb(160, 160, 160);
        border-radius: 50%;
    }

    .task-incomplete-icon {
        height: 20px;
        width: 20px;
        background-color: #9c1200;
        border-radius: 50%;
    }

    .delete-link {
        text-decoration: none;
        font-weight: 900;
        color: #9c1200;
        font-size: 22px;
        line-height: 0;
        padding: 20px 20px;
    }

    .delete-link:hover {
        font-size: 180%;
    }

    .task-wrapper:hover {
        background-color: #f7f7f7;
    }

    #search-add-wrapper {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 15px 25px 15px 25px;
    }

    input[type=text],
    input[type=password],
    textarea {
        border: 1px solid #757575;
        border-radius: 10px;
        padding: 10px;
        width: 50%;
        background: #fff;
    }


    .card-body input[type=text],
    .card-body input[type=password] {
        border: 1px solid #757575;
        border-radius: 10px;
        padding: 10px;
        width: 50%;
        background: #fff;
        margin-top: 25px;
    }


    #id_product_id,
    #id_quantity_of_product {
        border: 1px solid #757575;
        border-radius: 10px;
        padding: 10px;
        width: 50%;
        background: #fff;
        margin-top: 15px;
    }


    input[type=text]:focus,
    input[type=password]:focus,
    textarea:focus {
        outline: none;
        border: 1px solid #9c1200;
    }


    label {
        padding-top: 10px !important;
        display: block;
    }

    ::placeholder {
        font-weight: 300;
        opacity: 0.5;
    }

    .button {
        background: #9c1200;
        margin-top: 20px;
        width: 40%;
        padding: 10px;
        border-radius: 10px;
        color: white;
    }

    #add-link {
        color: #9c1200;
        text-decoration: none;
        font-size: 42px;
        text-shadow: 1px 1px #81413b;
    }

    .card-body {
        padding: 20px 0 20px 0px;
        text-align: center;
    }

</style>

<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>

<!-- <script src="{% static 'js/script.js' %}"></script> -->
<!-- <script src="../static/js/script.js"></script> -->

</html>

homepage/templates/order_delete.html
{% extends 'main.html' %}
{% block content %}
<div class="header-bar">
<h1>Видалити замовлення</h1>
<a href="{% url 'order' %}">&#215;</a>
</div>
<div class="center">
<form action="" method="POST">
    {% csrf_token %}
    <p>Ви впевнені, що хочете видалити замовлення "{{order.product_id}}"?</p>
    <input class="button" type="submit" value="Видалити">
</form>
</div>
<style>
    .center {
        margin: 0 0 20px 60px;
        width: 50%;
        padding: 20px;
    }
</style>
{% endblock content %}

homepage/templates/order_detail.html
{% extends 'main.html' %}
{% load floatmul %}
{% block content %}
<div class="header-bar">
    <h1>{{ order.product_id }}</h1>
    <a href="{% url 'order' %}">&#215;</a>
</div>
    <table>
        <tr>
            <td class="order-info">Ціна:</td>
            <td>{{ order.product_id.price }} грн</td>
        </tr>
        <tr>
            <td class="order-info">Тип:</td>
            <td>{{ order.product_id.wine_type }}</td>
        </tr>
        <tr>
            <td class="order-info">Замовлено:</td>
            <td>{{ order.quantity_of_product }} пляшок</td>
        </tr>
        <tr>
            <td class="order-info">Дата створення:</td>
            <td>{{ order.created_at }}</td>
        </tr>
        <tr>
            <td class="order-info">Оновлено:</td>
            <td>{{ order.last_updated_at }}</td>
        </tr>
        <tr>
            <td class="order-info">Статус:</td>
            <td>{{ order.order_status }}</td>
        </tr>
        <tr>
            <td class="order-info">Загальна ціна за замовлення:</td>
            <td>
                {% with total_price=order.product_id.price|floatmul:order.quantity_of_product %}
                {{ total_price }} грн
                {% endwith %}
            </td>
        </tr>
    </table>
<style>
    .order-info {
        font-weight: bold;
        padding-right: 10px;
    }
    table {
        padding-bottom: 45px;
        padding-top: 25px;
    }
    td {
        padding: 10px 10px 10px 70px;
    }
</style>
{% endblock content %}

homepage/templates/order_form.html
{% extends 'main.html' %}
{% block content %}
<div class="header-bar">
    <h1>Зробити замовлення</h1>
    <a href="{% url 'order' %}">&#215;</a>
</div>
<div class="center">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button" type="submit" value="Замовити">
    </form>
</div>
<style>
    .center {
        margin: 0 0 20px 80px;
        width: 50%;
        padding: 20px;
    }
</style>
{% endblock content %}

homepage/templates/userPage.html
{% extends 'main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <h1>Вітання! {{ request.user|title }}</h1>
        <h3>У Вас <i>{{ count }} {% if count == 1 %}не закрите замовлення{% else %}не закритих замовлень{% endif %}</i>
        </h3>
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'catalogue' %}" id="user_icon">
        <i class="fas fa-list-ul catalog-icon"></i>
        <p>Каталог</p>
    </a>
    <a href="{% url 'logout' %}" id="user_icon">
        <i class="fas fa-sign-out-alt"></i>
        <p>Вийти</p>
    </a>
    {% else %}
    <a href="{% url 'login' %}">Увійти</a>
    {% endif %}
</div>

<div id="search-add-wrapper">
    <form action="" method="get">
        <input type="text" name="search-area" placeholder="Пошук">
        <button type="submit" class="button">
            <i class="fas fa-search"></i> Знайти</button>
    </form>
    <a id="add-link" href="{% url 'order-create' %}">&#x2b;</a>
</div>

<div class="task-items-wrapper">
    {% for i in order %}
    <div class="task-wrapper">
        {% if i.order_status == "Закрито" %}
        <div class="task-title">
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'order-detail' i.id%}">{{ i.product_id }}</a></s></i>
        </div>
        <a class="delete-link" href="{% url 'order-delete' i.id %}"><i class="fas fa-trash"></i></a>
        {% else %}
        <div class="task-title">
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'order-detail' i.id%}">{{ i.product_id }}</a>
        </div>
        <a class="delete-link" href="{% url 'order-delete' i.id %}"><i class="fas fa-trash"></i></a>
        {% endif %}
    </div>
    {% empty %}
    <div class="task-wrapper">
        <h3>Немає замовлень</h3>
    </div>
    {% endfor %}
</div>
{% endblock content %}